# Generated by Django 3.2 on 2022-11-23 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_default_county',
            new_name='default_county',
        ),
    ]
